blank_issues_enabled: true
contact_links:
  - name: ğŸ†• Create new issue
    url: https://github.com/nicelizhi/go-admin-api
    about: The issue which is not created via https://github.com/nicelizhi/go-admin-api will be closed immediately.
  - name: ğŸ†• åˆ›å»ºä¸€ä¸ªæ–° Issue
    url: https://github.com/nicelizhi/go-admin-api
    about: ä¸æ˜¯ç”¨ https://github.com/nicelizhi/go-admin-api åˆ›å»ºçš„ issue ä¼šè¢«æœºå™¨äººè‡ªåŠ¨å…³é—­ã€‚
